import { IconColor } from "@bliro/common-types/icon/IconColor";
import { IconName } from "@bliro/common-types/icon/IconName";
import {
  AccessibilityIcon,
  ActivitySquareIcon,
  AlarmClockIcon,
  AlbumIcon,
  AlertOctagonIcon,
  AlertTriangleIcon,
  AmbulanceIcon,
  AmpersandIcon,
  AnchorIcon,
  AngryIcon,
  AnnoyedIcon,
  AnvilIcon,
  AppleIcon,
  AppWindowIcon,
  ArchiveIcon,
  AreaChartIcon,
  ArmchairIcon,
  ArrowBigDownDashIcon,
  ArrowBigDownIcon,
  ArrowBigLeftDashIcon,
  ArrowBigLeftIcon,
  ArrowBigRightDashIcon,
  ArrowBigRightIcon,
  ArrowBigUpDashIcon,
  ArrowBigUpIcon,
  ArrowDownLeftSquareIcon,
  ArrowDownRightSquareIcon,
  ArrowDownSquareIcon,
  ArrowLeftSquareIcon,
  ArrowRightIcon,
  ArrowRightSquareIcon,
  ArrowUpLeftSquareIcon,
  ArrowUpRightIcon,
  ArrowUpRightSquareIcon,
  ArrowUpSquareIcon,
  AsteriskSquareIcon,
  AtomIcon,
  AtSignIcon,
  AudioLinesIcon,
  AudioWaveformIcon,
  AwardIcon,
  AxeIcon,
  BabyIcon,
  BackpackIcon,
  BadgeHelpIcon,
  BananaIcon,
  BanknoteIcon,
  BarChart3Icon,
  BarChart4Icon,
  BarChartBigIcon,
  BarChartHorizontalBigIcon,
  BarChartHorizontalIcon,
  BathIcon,
  BatteryFullIcon,
  BatteryLowIcon,
  BedDoubleIcon,
  BeefIcon,
  BeerIcon,
  BellIcon,
  BellRingIcon,
  BikeIcon,
  BinaryIcon,
  BiohazardIcon,
  BirdIcon,
  BlendIcon,
  BluetoothIcon,
  BluetoothSearchingIcon,
  BoltIcon,
  BombIcon,
  BoneIcon,
  BookAIcon,
  BookCheckIcon,
  BookDownIcon,
  BookHeartIcon,
  BookIcon,
  BookKeyIcon,
  BookLockIcon,
  BookmarkCheckIcon,
  BookMarkedIcon,
  BookmarkIcon,
  BookmarkPlusIcon,
  BookOpenCheckIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BookPlusIcon,
  BookTextIcon,
  BookTypeIcon,
  BookUpIcon,
  BookUserIcon,
  BookXIcon,
  BotIcon,
  BoxesIcon,
  BoxIcon,
  BoxSelectIcon,
  BrainCircuitIcon,
  BrickWallIcon,
  BriefcaseIcon,
  BrushIcon,
  BugIcon,
  BugPlayIcon,
  Building2Icon,
  BuildingIcon,
  BusIcon,
  CableCarIcon,
  CableIcon,
  CakeIcon,
  CalendarCheck2Icon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CalendarFoldIcon,
  CalendarHeartIcon,
  CalendarIcon,
  CalendarMinusIcon,
  CalendarOffIcon,
  CalendarPlusIcon,
  CalendarRangeIcon,
  CalendarSearchIcon,
  CalendarX2Icon,
  CameraIcon,
  CameraOffIcon,
  CandlestickChartIcon,
  CandyCaneIcon,
  CandyIcon,
  CarFrontIcon,
  CarIcon,
  CarrotIcon,
  CassetteTapeIcon,
  CastIcon,
  CastleIcon,
  CatIcon,
  CctvIcon,
  CheckCheckIcon,
  CheckSquare2Icon,
  CheckSquareIcon,
  ChefHatIcon,
  CherryIcon,
  ChevronDownIcon,
  ChevronDownSquareIcon,
  ChevronLeftIcon,
  ChevronLeftSquareIcon,
  ChevronRightIcon,
  ChevronRightSquareIcon,
  ChevronsLeftRightIcon,
  ChevronUpIcon,
  ChevronUpSquareIcon,
  ChromeIcon,
  ChurchIcon,
  CircleDollarSignIcon,
  CircleIcon,
  CircleUserIcon,
  CitrusIcon,
  ClapperboardIcon,
  ClipboardCheckIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClipboardPasteIcon,
  ClipboardPenLineIcon,
  ClipboardTypeIcon,
  ClipboardXIcon,
  Clock2Icon,
  CloudCogIcon,
  CloudHailIcon,
  CloudIcon,
  CloudMoonIcon,
  CloudOffIcon,
  CloudSunIcon,
  CloudyIcon,
  CloverIcon,
  Code2Icon,
  CodeIcon,
  CodeSquareIcon,
  CoffeeIcon,
  CogIcon,
  CompassIcon,
  ComputerIcon,
  ConciergeBellIcon,
  ConeIcon,
  ConstructionIcon,
  ContactIcon,
  ContainerIcon,
  CookieIcon,
  CookingPotIcon,
  CopyIcon,
  CopyrightIcon,
  CpuIcon,
  CreativeCommonsIcon,
  CreditCardIcon,
  CroissantIcon,
  CrosshairIcon,
  CrossIcon,
  CrownIcon,
  CupSodaIcon,
  DatabaseIcon,
  DatabaseZapIcon,
  DeleteIcon,
  DiamondIcon,
  Dice6Icon,
  DicesIcon,
  DiffIcon,
  Disc2Icon,
  DiscIcon,
  DnaIcon,
  DogIcon,
  DollarSignIcon,
  DonutIcon,
  DoorClosedIcon,
  DownloadCloudIcon,
  DownloadIcon,
  DramaIcon,
  DribbbleIcon,
  DrillIcon,
  DropletsIcon,
  DrumIcon,
  DrumstickIcon,
  DumbbellIcon,
  EarIcon,
  EraserIcon,
  EuroIcon,
  ExpandIcon,
  EyeIcon,
  FastForwardIcon,
  FeatherIcon,
  FenceIcon,
  FerrisWheelIcon,
  FigmaIcon,
  FileAudioIcon,
  FileAxis3dIcon,
  FileBadgeIcon,
  FileBarChart2Icon,
  FileBarChartIcon,
  FileBoxIcon,
  FileCheck2Icon,
  FileClockIcon,
  FileCode2Icon,
  FileCogIcon,
  FileDiffIcon,
  FileDigitIcon,
  FileDownIcon,
  FileHeartIcon,
  FileIcon,
  FileImageIcon,
  FileInputIcon,
  FileJson2Icon,
  FileKey2Icon,
  FileLock2Icon,
  FileMinus2Icon,
  FileMusicIcon,
  FileOutputIcon,
  FilePenIcon,
  FilePenLineIcon,
  FilePieChartIcon,
  FilePlus2Icon,
  FileQuestionIcon,
  FileSearchIcon,
  FilesIcon,
  FileSlidersIcon,
  FileSpreadsheetIcon,
  FileSymlinkIcon,
  FileTerminalIcon,
  FileTextIcon,
  FileType2Icon,
  FileUpIcon,
  FileVolume2Icon,
  FileVolumeIcon,
  FileWarningIcon,
  FileX2Icon,
  FilmIcon,
  FilterIcon,
  FingerprintIcon,
  FireExtinguisherIcon,
  FishIcon,
  FlagIcon,
  FlameIcon,
  FlaskConicalIcon,
  FlaskRoundIcon,
  FlowerIcon,
  FolderClockIcon,
  FolderCogIcon,
  FolderHeartIcon,
  FolderIcon,
  FolderInputIcon,
  FolderKanbanIcon,
  FolderKeyIcon,
  FolderLockIcon,
  FolderOpenIcon,
  FolderOutputIcon,
  FolderPenIcon,
  FolderPlusIcon,
  FolderSearchIcon,
  FoldersIcon,
  FolderSyncIcon,
  FolderTreeIcon,
  FolderXIcon,
  FootprintsIcon,
  ForkliftIcon,
  FormInputIcon,
  ForwardIcon,
  FrameIcon,
  FrownIcon,
  FuelIcon,
  FullscreenIcon,
  Gamepad2Icon,
  GamepadIcon,
  GanttChartIcon,
  GanttChartSquareIcon,
  GaugeIcon,
  GavelIcon,
  GemIcon,
  GhostIcon,
  GiftIcon,
  GitCompareArrowsIcon,
  GitPullRequestArrowIcon,
  GlassesIcon,
  GlassWaterIcon,
  Globe2Icon,
  GlobeIcon,
  GraduationCapIcon,
  GrapeIcon,
  GuitarIcon,
  HammerIcon,
  HandHeartIcon,
  HandHelpingIcon,
  HandIcon,
  HandMetalIcon,
  HandshakeIcon,
  HardDriveDownloadIcon,
  HardDriveUploadIcon,
  HashIcon,
  HazeIcon,
  HeadphonesIcon,
  HeartCrackIcon,
  HeartHandshakeIcon,
  HeartIcon,
  HeartPulseIcon,
  HeaterIcon,
  HelpCircleIcon,
  HighlighterIcon,
  HistoryIcon,
  HomeIcon,
  HopIcon,
  HospitalIcon,
  HotelIcon,
  HourglassIcon,
  IceCream2Icon,
  IceCreamIcon,
  ImageIcon,
  ImageMinusIcon,
  ImagePlusIcon,
  ImportIcon,
  InboxIcon,
  InfinityIcon,
  InfoIcon,
  InstagramIcon,
  KanbanSquareIcon,
  KeyIcon,
  KeyRoundIcon,
  LampDeskIcon,
  LandmarkIcon,
  LandPlotIcon,
  LanguagesIcon,
  LaptopIcon,
  LaughIcon,
  Layers3Icon,
  LayoutDashboardIcon,
  LayoutGridIcon,
  LayoutListIcon,
  LeafIcon,
  LibraryBigIcon,
  LifeBuoyIcon,
  LightbulbIcon,
  LineChartIcon,
  Link2Icon,
  LinkIcon,
  ListChecksIcon,
  ListCollapseIcon,
  ListEndIcon,
  ListIcon,
  ListMinusIcon,
  ListOrderedIcon,
  ListPlusIcon,
  ListRestartIcon,
  ListStartIcon,
  ListTodoIcon,
  ListTreeIcon,
  ListVideoIcon,
  ListXIcon,
  LoaderIcon,
  LocateFixedIcon,
  LockIcon,
  LogInIcon,
  LogOutIcon,
  LollipopIcon,
  LucideProps,
  LuggageIcon,
  MagnetIcon,
  MailboxIcon,
  MailCheckIcon,
  MailIcon,
  MailMinusIcon,
  MailOpenIcon,
  MailPlusIcon,
  MailQuestionIcon,
  MailSearchIcon,
  MailWarningIcon,
  MailXIcon,
  MapIcon,
  MapPinnedIcon,
  MartiniIcon,
  Maximize2Icon,
  MedalIcon,
  MegaphoneIcon,
  MehIcon,
  MemoryStickIcon,
  MenuSquareIcon,
  MergeIcon,
  MessageCircleMoreIcon,
  MessageSquareCodeIcon,
  MessageSquareHeartIcon,
  MessageSquareIcon,
  MessageSquareMoreIcon,
  MessageSquarePlusIcon,
  MessageSquareQuoteIcon,
  MessageSquareShareIcon,
  MessageSquareTextIcon,
  MessageSquareWarningIcon,
  MessageSquareXIcon,
  MessagesSquareIcon,
  MicIcon,
  MicroscopeIcon,
  MicrowaveIcon,
  MilestoneIcon,
  MinusSquareIcon,
  MonitorCheckIcon,
  MonitorDownIcon,
  MonitorIcon,
  MonitorSmartphoneIcon,
  MonitorUpIcon,
  MonitorXIcon,
  MoonIcon,
  MountainSnowIcon,
  MousePointer2Icon,
  MousePointerClickIcon,
  MSquareIcon,
  Music2Icon,
  MusicIcon,
  NavigationIcon,
  NetworkIcon,
  NewspaperIcon,
  NotebookIcon,
  NotebookPenIcon,
  NotebookTextIcon,
  NotepadTextIcon,
  OutdentIcon,
  Package2Icon,
  PackageCheckIcon,
  PackageIcon,
  PackageOpenIcon,
  PaintbrushIcon,
  PaintBucketIcon,
  PaletteIcon,
  PalmtreeIcon,
  PaperclipIcon,
  ParenthesesIcon,
  PartyPopperIcon,
  PauseIcon,
  PauseOctagonIcon,
  PawPrintIcon,
  PcCaseIcon,
  PencilIcon,
  PencilLineIcon,
  PencilRulerIcon,
  PenIcon,
  PenToolIcon,
  PercentIcon,
  PercentSquareIcon,
  PersonStandingIcon,
  PhoneCallIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneMissedIcon,
  PhoneOutgoingIcon,
  PianoIcon,
  PieChartIcon,
  PiggyBankIcon,
  PillIcon,
  PinIcon,
  PipetteIcon,
  PizzaIcon,
  PlaneIcon,
  PlaneTakeoffIcon,
  PlaySquareIcon,
  Plug2Icon,
  PlusIcon,
  PlusSquareIcon,
  PocketIcon,
  PocketKnifeIcon,
  PodcastIcon,
  PointerIcon,
  PointerOffIcon,
  PopcornIcon,
  PopsicleIcon,
  PowerSquareIcon,
  PresentationIcon,
  PrinterIcon,
  ProjectorIcon,
  PuzzleIcon,
  PyramidIcon,
  QrCodeIcon,
  QuoteIcon,
  RabbitIcon,
  RadiationIcon,
  RadioIcon,
  RadioTowerIcon,
  RailSymbolIcon,
  RainbowIcon,
  RatIcon,
  RecycleIcon,
  RefreshCwIcon,
  RocketIcon,
  RockingChairIcon,
  RollerCoasterIcon,
  Rotate3dIcon,
  RouterIcon,
  RssIcon,
  RulerIcon,
  SailboatIcon,
  SatelliteDishIcon,
  SaveIcon,
  ScaleIcon,
  ScanEyeIcon,
  ScanFaceIcon,
  ScanSearchIcon,
  ScanTextIcon,
  ScatterChartIcon,
  School2Icon,
  SchoolIcon,
  ScissorsIcon,
  ScreenShareIcon,
  ScreenShareOffIcon,
  ScrollTextIcon,
  SearchIcon,
  SendIcon,
  ServerCrashIcon,
  ServerIcon,
  SettingsIcon,
  ShapesIcon,
  Share2Icon,
  ShareIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShieldPlusIcon,
  ShieldQuestionIcon,
  ShieldXIcon,
  ShipIcon,
  ShipWheelIcon,
  ShirtIcon,
  ShoppingCartIcon,
  ShowerHeadIcon,
  ShrinkIcon,
  ShrubIcon,
  ShuffleIcon,
  SigmaSquareIcon,
  SignpostBigIcon,
  SirenIcon,
  SkullIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  SmileIcon,
  SmilePlusIcon,
  SnailIcon,
  SnowflakeIcon,
  SoupIcon,
  SpadeIcon,
  SparklesIcon,
  SpeakerIcon,
  SpeechIcon,
  SplitIcon,
  SprayCanIcon,
  SproutIcon,
  SquareDashedBottomCodeIcon,
  SquarePenIcon,
  SquareUserIcon,
  SquirrelIcon,
  StampIcon,
  StarIcon,
  StethoscopeIcon,
  StoreIcon,
  SubtitlesIcon,
  SunIcon,
  SunriseIcon,
  SunsetIcon,
  SwatchBookIcon,
  SwordsIcon,
  SyringeIcon,
  TabletIcon,
  TabletsIcon,
  TagIcon,
  TargetIcon,
  TentIcon,
  TentTreeIcon,
  TerminalIcon,
  TerminalSquareIcon,
  TestTube2Icon,
  TextIcon,
  TextSearchIcon,
  TheaterIcon,
  ThermometerSnowflakeIcon,
  ThermometerSunIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TicketIcon,
  TicketPercentIcon,
  TimerIcon,
  ToggleLeftIcon,
  TowerControlIcon,
  TractorIcon,
  TrafficConeIcon,
  TrainFrontIcon,
  TrainTrackIcon,
  Trash2Icon,
  TreePineIcon,
  TreesIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TriangleIcon,
  TrophyIcon,
  TruckIcon,
  TurtleIcon,
  TvIcon,
  TypeIcon,
  UmbrellaIcon,
  UnlinkIcon,
  UnlockKeyholeIcon,
  UnplugIcon,
  UploadCloudIcon,
  UploadIcon,
  UsbIcon,
  UserCheckIcon,
  UserCogIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UserSearchIcon,
  UsersIcon,
  UserXIcon,
  UtensilsIcon,
  VeganIcon,
  VenetianMaskIcon,
  VideoIcon,
  VideotapeIcon,
  ViewIcon,
  Volume2Icon,
  VolumeXIcon,
  WalletIcon,
  WallpaperIcon,
  Wand2Icon,
  WandIcon,
  WarehouseIcon,
  WatchIcon,
  WavesIcon,
  WaypointsIcon,
  WebcamIcon,
  WebhookIcon,
  WheatIcon,
  WifiIcon,
  WineIcon,
  WrenchIcon,
  XOctagonIcon,
  XSquareIcon,
  ZapIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "lucide-react";
import { ComponentType } from "react";

import { getIconColor } from "./IconColor.js";

export interface IconProps {
  color: IconColor;
  name: IconName;
  size: number;
}

const iconNameToLucideIcon: Record<IconName, ComponentType<LucideProps>> = {
  accessibility: AccessibilityIcon,
  "activity-square": ActivitySquareIcon,
  "alarm-clock": AlarmClockIcon,
  album: AlbumIcon,
  "alert-octagon": AlertOctagonIcon,
  "alert-triangle": AlertTriangleIcon,
  ambulance: AmbulanceIcon,
  ampersand: AmpersandIcon,
  anchor: AnchorIcon,
  angry: AngryIcon,
  annoyed: AnnoyedIcon,
  anvil: AnvilIcon,
  "app-window": AppWindowIcon,
  apple: AppleIcon,
  archive: ArchiveIcon,
  "area-chart": AreaChartIcon,
  armchair: ArmchairIcon,
  "arrow-big-down-dash": ArrowBigDownDashIcon,
  "arrow-big-down": ArrowBigDownIcon,
  "arrow-big-left-dash": ArrowBigLeftDashIcon,
  "arrow-big-left": ArrowBigLeftIcon,
  "arrow-big-right-dash": ArrowBigRightDashIcon,
  "arrow-big-right": ArrowBigRightIcon,
  "arrow-big-up-dash": ArrowBigUpDashIcon,
  "arrow-big-up": ArrowBigUpIcon,
  "arrow-down-left-square": ArrowDownLeftSquareIcon,
  "arrow-down-right-square": ArrowDownRightSquareIcon,
  "arrow-down-square": ArrowDownSquareIcon,
  "arrow-left-square": ArrowLeftSquareIcon,
  "arrow-right-square": ArrowRightSquareIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up-left-square": ArrowUpLeftSquareIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "arrow-up-right-square": ArrowUpRightSquareIcon,
  "arrow-up-square": ArrowUpSquareIcon,
  "asterisk-square": AsteriskSquareIcon,
  "at-sign": AtSignIcon,
  atom: AtomIcon,
  "audio-lines": AudioLinesIcon,
  "audio-waveform": AudioWaveformIcon,
  award: AwardIcon,
  axe: AxeIcon,
  baby: BabyIcon,
  backpack: BackpackIcon,
  "badge-question-mark": BadgeHelpIcon,
  banana: BananaIcon,
  banknote: BanknoteIcon,
  "bar-chart-3": BarChart3Icon,
  "bar-chart-4": BarChart4Icon,
  "bar-chart-big": BarChartBigIcon,
  "bar-chart-horizontal-big": BarChartHorizontalBigIcon,
  "bar-chart-horizontal": BarChartHorizontalIcon,
  bath: BathIcon,
  "battery-full": BatteryFullIcon,
  "battery-low": BatteryLowIcon,
  "bed-double": BedDoubleIcon,
  beef: BeefIcon,
  beer: BeerIcon,
  bell: BellIcon,
  "bell-ring": BellRingIcon,
  bike: BikeIcon,
  binary: BinaryIcon,
  biohazard: BiohazardIcon,
  bird: BirdIcon,
  blend: BlendIcon,
  bluetooth: BluetoothIcon,
  "bluetooth-searching": BluetoothSearchingIcon,
  bolt: BoltIcon,
  bomb: BombIcon,
  bone: BoneIcon,
  "book-a": BookAIcon,
  "book-check": BookCheckIcon,
  "book-down": BookDownIcon,
  "book-heart": BookHeartIcon,
  book: BookIcon,
  "book-key": BookKeyIcon,
  "book-lock": BookLockIcon,
  "book-marked": BookMarkedIcon,
  "book-open-check": BookOpenCheckIcon,
  "book-open": BookOpenIcon,
  "book-open-text": BookOpenTextIcon,
  "book-plus": BookPlusIcon,
  "book-text": BookTextIcon,
  "book-type": BookTypeIcon,
  "book-up": BookUpIcon,
  "book-user": BookUserIcon,
  "book-x": BookXIcon,
  "bookmark-check": BookmarkCheckIcon,
  bookmark: BookmarkIcon,
  "bookmark-plus": BookmarkPlusIcon,
  bot: BotIcon,
  box: BoxIcon,
  "box-select": BoxSelectIcon,
  boxes: BoxesIcon,
  "brain-circuit": BrainCircuitIcon,
  "brick-wall": BrickWallIcon,
  briefcase: BriefcaseIcon,
  brush: BrushIcon,
  bug: BugIcon,
  "bug-play": BugPlayIcon,
  building: BuildingIcon,
  "building-2": Building2Icon,
  bus: BusIcon,
  "cable-car": CableCarIcon,
  cable: CableIcon,
  cake: CakeIcon,
  "calendar-check-2": CalendarCheck2Icon,
  "calendar-clock": CalendarClockIcon,
  "calendar-days": CalendarDaysIcon,
  "calendar-fold": CalendarFoldIcon,
  "calendar-heart": CalendarHeartIcon,
  "calendar-minus": CalendarMinusIcon,
  "calendar-off": CalendarOffIcon,
  "calendar-plus": CalendarPlusIcon,
  "calendar-range": CalendarRangeIcon,
  "calendar-search": CalendarSearchIcon,
  "calendar-x-2": CalendarX2Icon,
  calendar: CalendarIcon,
  camera: CameraIcon,
  "camera-off": CameraOffIcon,
  "candlestick-chart": CandlestickChartIcon,
  candy: CandyIcon,
  "candy-cane": CandyCaneIcon,
  "car-front": CarFrontIcon,
  car: CarIcon,
  carrot: CarrotIcon,
  "cassette-tape": CassetteTapeIcon,
  cast: CastIcon,
  castle: CastleIcon,
  cat: CatIcon,
  cctv: CctvIcon,
  "check-check": CheckCheckIcon,
  "check-square": CheckSquareIcon,
  "check-square-2": CheckSquare2Icon,
  "chef-hat": ChefHatIcon,
  cherry: CherryIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-down-square": ChevronDownSquareIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-left-square": ChevronLeftSquareIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-right-square": ChevronRightSquareIcon,
  "chevron-up": ChevronUpIcon,
  "chevron-up-square": ChevronUpSquareIcon,
  "chevrons-left-right": ChevronsLeftRightIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  chrome: ChromeIcon,
  church: ChurchIcon,
  "circle-dollar-sign": CircleDollarSignIcon,
  circle: CircleIcon,
  "circle-user": CircleUserIcon,
  citrus: CitrusIcon,
  clapperboard: ClapperboardIcon,
  "clipboard-check": ClipboardCheckIcon,
  "clipboard-copy": ClipboardCopyIcon,
  clipboard: ClipboardIcon,
  "clipboard-list": ClipboardListIcon,
  "clipboard-paste": ClipboardPasteIcon,
  "clipboard-pen-line": ClipboardPenLineIcon,
  "clipboard-type": ClipboardTypeIcon,
  "clipboard-x": ClipboardXIcon,
  "clock-2": Clock2Icon,
  "cloud-cog": CloudCogIcon,
  "cloud-hail": CloudHailIcon,
  cloud: CloudIcon,
  "cloud-moon": CloudMoonIcon,
  "cloud-off": CloudOffIcon,
  "cloud-sun": CloudSunIcon,
  cloudy: CloudyIcon,
  clover: CloverIcon,
  code: CodeIcon,
  "code-2": Code2Icon,
  "code-square": CodeSquareIcon,
  coffee: CoffeeIcon,
  cog: CogIcon,
  compass: CompassIcon,
  computer: ComputerIcon,
  "concierge-bell": ConciergeBellIcon,
  cone: ConeIcon,
  construction: ConstructionIcon,
  contact: ContactIcon,
  container: ContainerIcon,
  cookie: CookieIcon,
  "cooking-pot": CookingPotIcon,
  copy: CopyIcon,
  copyright: CopyrightIcon,
  cpu: CpuIcon,
  "creative-commons": CreativeCommonsIcon,
  "credit-card": CreditCardIcon,
  croissant: CroissantIcon,
  cross: CrossIcon,
  crosshair: CrosshairIcon,
  crown: CrownIcon,
  "cup-soda": CupSodaIcon,
  database: DatabaseIcon,
  "database-zap": DatabaseZapIcon,
  delete: DeleteIcon,
  diamond: DiamondIcon,
  "dice-6": Dice6Icon,
  dices: DicesIcon,
  diff: DiffIcon,
  disc: DiscIcon,
  "disc-2": Disc2Icon,
  dna: DnaIcon,
  dog: DogIcon,
  "dollar-sign": DollarSignIcon,
  donut: DonutIcon,
  "door-closed": DoorClosedIcon,
  "download-cloud": DownloadCloudIcon,
  download: DownloadIcon,
  drama: DramaIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  dribbble: DribbbleIcon,
  drill: DrillIcon,
  droplets: DropletsIcon,
  drum: DrumIcon,
  drumstick: DrumstickIcon,
  dumbbell: DumbbellIcon,
  ear: EarIcon,
  eraser: EraserIcon,
  euro: EuroIcon,
  expand: ExpandIcon,
  eye: EyeIcon,
  "fast-forward": FastForwardIcon,
  feather: FeatherIcon,
  fence: FenceIcon,
  "ferris-wheel": FerrisWheelIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  figma: FigmaIcon,
  file: FileIcon,
  "file-audio": FileAudioIcon,
  "file-axis-3d": FileAxis3dIcon,
  "file-badge": FileBadgeIcon,
  "file-bar-chart": FileBarChartIcon,
  "file-bar-chart-2": FileBarChart2Icon,
  "file-box": FileBoxIcon,
  "file-check-2": FileCheck2Icon,
  "file-clock": FileClockIcon,
  "file-code-2": FileCode2Icon,
  "file-cog": FileCogIcon,
  "file-diff": FileDiffIcon,
  "file-digit": FileDigitIcon,
  "file-down": FileDownIcon,
  "file-heart": FileHeartIcon,
  "file-image": FileImageIcon,
  "file-input": FileInputIcon,
  "file-json-2": FileJson2Icon,
  "file-key-2": FileKey2Icon,
  "file-lock-2": FileLock2Icon,
  "file-minus-2": FileMinus2Icon,
  "file-music": FileMusicIcon,
  "file-output": FileOutputIcon,
  "file-pen": FilePenIcon,
  "file-pen-line": FilePenLineIcon,
  "file-pie-chart": FilePieChartIcon,
  "file-plus-2": FilePlus2Icon,
  "file-question": FileQuestionIcon,
  "file-search": FileSearchIcon,
  "file-sliders": FileSlidersIcon,
  "file-spreadsheet": FileSpreadsheetIcon,
  "file-symlink": FileSymlinkIcon,
  "file-terminal": FileTerminalIcon,
  "file-text": FileTextIcon,
  "file-type-2": FileType2Icon,
  "file-up": FileUpIcon,
  "file-volume": FileVolumeIcon,
  "file-volume-2": FileVolume2Icon,
  "file-warning": FileWarningIcon,
  "file-x-2": FileX2Icon,
  files: FilesIcon,
  film: FilmIcon,
  filter: FilterIcon,
  fingerprint: FingerprintIcon,
  "fire-extinguisher": FireExtinguisherIcon,
  fish: FishIcon,
  flag: FlagIcon,
  flame: FlameIcon,
  "flask-conical": FlaskConicalIcon,
  "flask-round": FlaskRoundIcon,
  flower: FlowerIcon,
  folder: FolderIcon,
  "folder-clock": FolderClockIcon,
  "folder-cog": FolderCogIcon,
  "folder-heart": FolderHeartIcon,
  "folder-input": FolderInputIcon,
  "folder-kanban": FolderKanbanIcon,
  "folder-key": FolderKeyIcon,
  "folder-lock": FolderLockIcon,
  "folder-open": FolderOpenIcon,
  "folder-output": FolderOutputIcon,
  "folder-pen": FolderPenIcon,
  "folder-plus": FolderPlusIcon,
  "folder-search": FolderSearchIcon,
  "folder-sync": FolderSyncIcon,
  "folder-tree": FolderTreeIcon,
  "folder-x": FolderXIcon,
  folders: FoldersIcon,
  footprints: FootprintsIcon,
  forklift: ForkliftIcon,
  "form-input": FormInputIcon,
  forward: ForwardIcon,
  frame: FrameIcon,
  frown: FrownIcon,
  fuel: FuelIcon,
  fullscreen: FullscreenIcon,
  gamepad: GamepadIcon,
  "gamepad-2": Gamepad2Icon,
  "gantt-chart": GanttChartIcon,
  "gantt-chart-square": GanttChartSquareIcon,
  gauge: GaugeIcon,
  gavel: GavelIcon,
  gem: GemIcon,
  ghost: GhostIcon,
  gift: GiftIcon,
  "git-compare-arrows": GitCompareArrowsIcon,
  "git-pull-request-arrow": GitPullRequestArrowIcon,
  "glass-water": GlassWaterIcon,
  glasses: GlassesIcon,
  globe: GlobeIcon,
  "globe-2": Globe2Icon,
  "graduation-cap": GraduationCapIcon,
  grape: GrapeIcon,
  guitar: GuitarIcon,
  hammer: HammerIcon,
  hand: HandIcon,
  "hand-heart": HandHeartIcon,
  "hand-helping": HandHelpingIcon,
  "hand-metal": HandMetalIcon,
  handshake: HandshakeIcon,
  "hard-drive-download": HardDriveDownloadIcon,
  "hard-drive-upload": HardDriveUploadIcon,
  hash: HashIcon,
  haze: HazeIcon,
  headphones: HeadphonesIcon,
  heart: HeartIcon,
  "heart-crack": HeartCrackIcon,
  "heart-handshake": HeartHandshakeIcon,
  "heart-pulse": HeartPulseIcon,
  heater: HeaterIcon,
  "help-circle": HelpCircleIcon,
  highlighter: HighlighterIcon,
  history: HistoryIcon,
  home: HomeIcon,
  hop: HopIcon,
  hospital: HospitalIcon,
  hotel: HotelIcon,
  hourglass: HourglassIcon,
  "ice-cream": IceCreamIcon,
  "ice-cream-2": IceCream2Icon,
  image: ImageIcon,
  "image-minus": ImageMinusIcon,
  "image-plus": ImagePlusIcon,
  import: ImportIcon,
  inbox: InboxIcon,
  infinity: InfinityIcon,
  info: InfoIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  instagram: InstagramIcon,
  "kanban-square": KanbanSquareIcon,
  key: KeyIcon,
  "key-round": KeyRoundIcon,
  "lamp-desk": LampDeskIcon,
  "land-plot": LandPlotIcon,
  landmark: LandmarkIcon,
  languages: LanguagesIcon,
  laptop: LaptopIcon,
  laugh: LaughIcon,
  "layers-3": Layers3Icon,
  "layout-dashboard": LayoutDashboardIcon,
  "layout-grid": LayoutGridIcon,
  "layout-list": LayoutListIcon,
  leaf: LeafIcon,
  "library-big": LibraryBigIcon,
  "life-buoy": LifeBuoyIcon,
  lightbulb: LightbulbIcon,
  "line-chart": LineChartIcon,
  link: LinkIcon,
  "link-2": Link2Icon,
  list: ListIcon,
  "list-checks": ListChecksIcon,
  "list-collapse": ListCollapseIcon,
  "list-end": ListEndIcon,
  "list-minus": ListMinusIcon,
  "list-ordered": ListOrderedIcon,
  "list-plus": ListPlusIcon,
  "list-restart": ListRestartIcon,
  "list-start": ListStartIcon,
  "list-todo": ListTodoIcon,
  "list-tree": ListTreeIcon,
  "list-video": ListVideoIcon,
  "list-x": ListXIcon,
  loader: LoaderIcon,
  "locate-fixed": LocateFixedIcon,
  lock: LockIcon,
  "log-in": LogInIcon,
  "log-out": LogOutIcon,
  lollipop: LollipopIcon,
  luggage: LuggageIcon,
  "m-square": MSquareIcon,
  magnet: MagnetIcon,
  mail: MailIcon,
  "mail-check": MailCheckIcon,
  "mail-minus": MailMinusIcon,
  "mail-open": MailOpenIcon,
  "mail-plus": MailPlusIcon,
  "mail-question": MailQuestionIcon,
  "mail-search": MailSearchIcon,
  "mail-warning": MailWarningIcon,
  "mail-x": MailXIcon,
  mailbox: MailboxIcon,
  map: MapIcon,
  "map-pinned": MapPinnedIcon,
  martini: MartiniIcon,
  "maximize-2": Maximize2Icon,
  medal: MedalIcon,
  megaphone: MegaphoneIcon,
  meh: MehIcon,
  "memory-stick": MemoryStickIcon,
  "menu-square": MenuSquareIcon,
  merge: MergeIcon,
  "message-circle-more": MessageCircleMoreIcon,
  "message-square": MessageSquareIcon,
  "message-square-code": MessageSquareCodeIcon,
  "message-square-heart": MessageSquareHeartIcon,
  "message-square-more": MessageSquareMoreIcon,
  "message-square-plus": MessageSquarePlusIcon,
  "message-square-quote": MessageSquareQuoteIcon,
  "message-square-share": MessageSquareShareIcon,
  "message-square-text": MessageSquareTextIcon,
  "message-square-warning": MessageSquareWarningIcon,
  "message-square-x": MessageSquareXIcon,
  "messages-square": MessagesSquareIcon,
  mic: MicIcon,
  microscope: MicroscopeIcon,
  microwave: MicrowaveIcon,
  milestone: MilestoneIcon,
  "minus-square": MinusSquareIcon,
  monitor: MonitorIcon,
  "monitor-check": MonitorCheckIcon,
  "monitor-down": MonitorDownIcon,
  "monitor-smartphone": MonitorSmartphoneIcon,
  "monitor-up": MonitorUpIcon,
  "monitor-x": MonitorXIcon,
  moon: MoonIcon,
  "mountain-snow": MountainSnowIcon,
  "mouse-pointer-2": MousePointer2Icon,
  "mouse-pointer-click": MousePointerClickIcon,
  music: MusicIcon,
  "music-2": Music2Icon,
  navigation: NavigationIcon,
  network: NetworkIcon,
  newspaper: NewspaperIcon,
  notebook: NotebookIcon,
  "notebook-pen": NotebookPenIcon,
  "notebook-text": NotebookTextIcon,
  "notepad-text": NotepadTextIcon,
  outdent: OutdentIcon,
  package: PackageIcon,
  "package-2": Package2Icon,
  "package-check": PackageCheckIcon,
  "package-open": PackageOpenIcon,
  "paint-bucket": PaintBucketIcon,
  paintbrush: PaintbrushIcon,
  palette: PaletteIcon,
  palmtree: PalmtreeIcon,
  paperclip: PaperclipIcon,
  parentheses: ParenthesesIcon,
  "party-popper": PartyPopperIcon,
  pause: PauseIcon,
  "pause-octagon": PauseOctagonIcon,
  "paw-print": PawPrintIcon,
  "pc-case": PcCaseIcon,
  pen: PenIcon,
  "pen-tool": PenToolIcon,
  pencil: PencilIcon,
  "pencil-line": PencilLineIcon,
  "pencil-ruler": PencilRulerIcon,
  percent: PercentIcon,
  "percent-square": PercentSquareIcon,
  "person-standing": PersonStandingIcon,
  phone: PhoneIcon,
  "phone-call": PhoneCallIcon,
  "phone-incoming": PhoneIncomingIcon,
  "phone-missed": PhoneMissedIcon,
  "phone-outgoing": PhoneOutgoingIcon,
  piano: PianoIcon,
  "pie-chart": PieChartIcon,
  "piggy-bank": PiggyBankIcon,
  pill: PillIcon,
  pin: PinIcon,
  pipette: PipetteIcon,
  pizza: PizzaIcon,
  plane: PlaneIcon,
  "plane-takeoff": PlaneTakeoffIcon,
  "play-square": PlaySquareIcon,
  "plug-2": Plug2Icon,
  plus: PlusIcon,
  "plus-square": PlusSquareIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  pocket: PocketIcon,
  "pocket-knife": PocketKnifeIcon,
  podcast: PodcastIcon,
  pointer: PointerIcon,
  "pointer-off": PointerOffIcon,
  popcorn: PopcornIcon,
  popsicle: PopsicleIcon,
  "power-square": PowerSquareIcon,
  presentation: PresentationIcon,
  printer: PrinterIcon,
  projector: ProjectorIcon,
  puzzle: PuzzleIcon,
  pyramid: PyramidIcon,
  "qr-code": QrCodeIcon,
  quote: QuoteIcon,
  rabbit: RabbitIcon,
  radiation: RadiationIcon,
  radio: RadioIcon,
  "radio-tower": RadioTowerIcon,
  // oxlint-disable-next-line typescript/no-deprecated
  "rail-symbol": RailSymbolIcon,
  rainbow: RainbowIcon,
  rat: RatIcon,
  recycle: RecycleIcon,
  "refresh-cw": RefreshCwIcon,
  rocket: RocketIcon,
  "rocking-chair": RockingChairIcon,
  "roller-coaster": RollerCoasterIcon,
  "rotate-3d": Rotate3dIcon,
  router: RouterIcon,
  rss: RssIcon,
  ruler: RulerIcon,
  sailboat: SailboatIcon,
  "satellite-dish": SatelliteDishIcon,
  save: SaveIcon,
  scale: ScaleIcon,
  "scan-eye": ScanEyeIcon,
  "scan-face": ScanFaceIcon,
  "scan-search": ScanSearchIcon,
  "scan-text": ScanTextIcon,
  "scatter-chart": ScatterChartIcon,
  school: SchoolIcon,
  "school-2": School2Icon,
  scissors: ScissorsIcon,
  "screen-share": ScreenShareIcon,
  "screen-share-off": ScreenShareOffIcon,
  "scroll-text": ScrollTextIcon,
  search: SearchIcon,
  send: SendIcon,
  server: ServerIcon,
  "server-crash": ServerCrashIcon,
  settings: SettingsIcon,
  shapes: ShapesIcon,
  share: ShareIcon,
  "share-2": Share2Icon,
  "shield-alert": ShieldAlertIcon,
  "shield-check": ShieldCheckIcon,
  "shield-plus": ShieldPlusIcon,
  "shield-question": ShieldQuestionIcon,
  "shield-x": ShieldXIcon,
  ship: ShipIcon,
  "ship-wheel": ShipWheelIcon,
  shirt: ShirtIcon,
  "shopping-cart": ShoppingCartIcon,
  "shower-head": ShowerHeadIcon,
  shrink: ShrinkIcon,
  shrub: ShrubIcon,
  shuffle: ShuffleIcon,
  "sigma-square": SigmaSquareIcon,
  "signpost-big": SignpostBigIcon,
  siren: SirenIcon,
  skull: SkullIcon,
  "sliders-horizontal": SlidersHorizontalIcon,
  smile: SmileIcon,
  "smile-plus": SmilePlusIcon,
  smartphone: SmartphoneIcon,
  snail: SnailIcon,
  snowflake: SnowflakeIcon,
  soup: SoupIcon,
  spade: SpadeIcon,
  sparkles: SparklesIcon,
  speaker: SpeakerIcon,
  speech: SpeechIcon,
  split: SplitIcon,
  "spray-can": SprayCanIcon,
  sprout: SproutIcon,
  "square-dashed-bottom-code": SquareDashedBottomCodeIcon,
  "square-pen": SquarePenIcon,
  "square-user": SquareUserIcon,
  squirrel: SquirrelIcon,
  stamp: StampIcon,
  star: StarIcon,
  stethoscope: StethoscopeIcon,
  store: StoreIcon,
  subtitles: SubtitlesIcon,
  sun: SunIcon,
  sunrise: SunriseIcon,
  sunset: SunsetIcon,
  "swatch-book": SwatchBookIcon,
  swords: SwordsIcon,
  syringe: SyringeIcon,
  tablet: TabletIcon,
  tablets: TabletsIcon,
  tag: TagIcon,
  target: TargetIcon,
  tent: TentIcon,
  "tent-tree": TentTreeIcon,
  terminal: TerminalIcon,
  "terminal-square": TerminalSquareIcon,
  "test-tube-2": TestTube2Icon,
  text: TextIcon,
  "text-search": TextSearchIcon,
  theater: TheaterIcon,
  "thermometer-snowflake": ThermometerSnowflakeIcon,
  "thermometer-sun": ThermometerSunIcon,
  "thumbs-down": ThumbsDownIcon,
  "thumbs-up": ThumbsUpIcon,
  ticket: TicketIcon,
  "ticket-percent": TicketPercentIcon,
  timer: TimerIcon,
  "toggle-left": ToggleLeftIcon,
  "tower-control": TowerControlIcon,
  tractor: TractorIcon,
  "traffic-cone": TrafficConeIcon,
  "train-front": TrainFrontIcon,
  "train-track": TrainTrackIcon,
  "trash-2": Trash2Icon,
  "tree-pine": TreePineIcon,
  trees: TreesIcon,
  "trending-down": TrendingDownIcon,
  "trending-up": TrendingUpIcon,
  triangle: TriangleIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  turtle: TurtleIcon,
  tv: TvIcon,
  type: TypeIcon,
  umbrella: UmbrellaIcon,
  unlink: UnlinkIcon,
  "unlock-keyhole": UnlockKeyholeIcon,
  unplug: UnplugIcon,
  upload: UploadIcon,
  "upload-cloud": UploadCloudIcon,
  usb: UsbIcon,
  user: UserIcon,
  "user-check": UserCheckIcon,
  "user-cog": UserCogIcon,
  "user-minus": UserMinusIcon,
  "user-plus": UserPlusIcon,
  "user-search": UserSearchIcon,
  "user-x": UserXIcon,
  users: UsersIcon,
  utensils: UtensilsIcon,
  vegan: VeganIcon,
  "venetian-mask": VenetianMaskIcon,
  video: VideoIcon,
  videotape: VideotapeIcon,
  view: ViewIcon,
  "volume-2": Volume2Icon,
  "volume-x": VolumeXIcon,
  wallet: WalletIcon,
  wallpaper: WallpaperIcon,
  wand: WandIcon,
  "wand-2": Wand2Icon,
  warehouse: WarehouseIcon,
  watch: WatchIcon,
  waves: WavesIcon,
  waypoints: WaypointsIcon,
  webcam: WebcamIcon,
  webhook: WebhookIcon,
  wheat: WheatIcon,
  wifi: WifiIcon,
  wine: WineIcon,
  wrench: WrenchIcon,
  "x-octagon": XOctagonIcon,
  "x-square": XSquareIcon,
  zap: ZapIcon,
  "zoom-in": ZoomInIcon,
  "zoom-out": ZoomOutIcon,
};

export function Icon({ color, name, size }: IconProps) {
  const LucideIcon = iconNameToLucideIcon[name] ?? BarChartBigIcon;
  return <LucideIcon size={size} color={getIconColor(color)} />;
}
